# Reference: https://github.com/actions/labeler

Test:
  - Tests/**/*

Documentation:
  - ./**/*.md

PackageUpdate:
  - ./Package.swift

GitHubAction:
  - .github/**/*

String:
  - Sources/String/**/*

Collection:
  - Sources/Collection/**/*

Array:
  - Sources/Collection/**/ArrayExtensions.swift
